FROM gliderlabs/alpine:3.3

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --no-cache openjdk8
RUN apk add --no-cache maven@testing

COPY maven-repo /maven-repo
COPY settings.xml.docker /settings.xml
COPY repos/<%= project %> /project

ENTRYPOINT /usr/share/java/maven-3.3.3/bin/mvn -f /project --settings=/settings.xml exec:java
